services:
  server:
    networks:
      - backend
    build:
      context: ./backend
    ports:
      - 9000:80
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: 'mysql:dbname=task;host=db'
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./app/:/var/www/html/
  db:
    container_name: db  
    networks:
      - backend
    image: postgres:14.8-alpine3.18
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
      - .docker/init.sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${MARIADB_DATABASE}
      POSTGRES_USER: ${MARIADB_ROOT_PASSWORD}
      POSTGRES_PASSWORD: ${MARIADB_USER}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:5173'

secrets:
  db_secret:
    file: ./secrets/db.txt

volumes:
  db-data:

networks:
  backend: